
"use client";
import React, { useEffect, useRef } from "react";
import gsap from "gsap";


export default function PrivacyPolicy() {
	const containerRef = useRef(null);
	const sectionRefs = useRef([]);

	useEffect(() => {
		gsap.from(containerRef.current, {
			opacity: 0,
			y: 40,
			duration: 0.8,
			ease: "power2.out"
		});
		gsap.from(sectionRefs.current, {
			opacity: 0,
			y: 30,
			stagger: 0.12,
			duration: 0.7,
			delay: 0.3,
			ease: "power2.out"
		});
	}, []);

	// List of all sections
	const sections = [
		{
			title: "Introduction",
			content: (
				<p className="text-gray-700">This Privacy Policy explains how HIJR portal ("HIJR", "we", "us", "our") collects, uses, shares, and safeguards Personal Data when you use our websites, mobile applications, and services that connect healthcare Candidates and Employers (the "Services").<br/>By using the Services, you agree to this Policy and to our Terms of Use.</p>
			)
		},
		{
			title: "1. Who we are and scope",
			content: (
				<p className="text-gray-700">HIJR operates a digital marketplace for healthcare recruitment (clinical and allied roles). This Policy applies to all users—Candidates, Employers, and visitors—and to all interactions with the Services, including browsing, profile creation, job posting/applying, messaging, scheduling, and payments (if applicable).</p>
			)
		},
		{
			title: "2. Key definitions",
			content: (
				<ul className="list-disc list-inside text-gray-700 space-y-2">
					<li><strong>Candidate:</strong> An individual searching for employment openings, services, or information related to their personal employment or job search</li>
					<li><strong>Employer:</strong> Individuals and/or organizations seeking information related to hiring or human resources, seeking candidate, or seeking to make available information regarding employment openings, on their behalf or other's behalf, including but not limited to agencies purchasing for multiple parties and employment agencies</li>
					<li><strong>Personal Data:</strong> Any information that can identify you (e.g., name, phone, email, resume details, device identifiers, IP address).</li>
					<li><strong>Processing:</strong> Any operation on Personal Data (collection, storage, use, sharing, deletion, etc.).</li>
					<li><strong>Data Fiduciary / Controller:</strong> The entity that decides why and how Personal Data is processed. For most processing described here, HIJR Jobs is the Data Fiduciary.</li>
					<li><strong>Processor:</strong> An entity which processes data in a particular way, at the direction of a controller.</li>
					<li><strong>Disposition Data:</strong> Application outcome signals (e.g., viewed, shortlisted, interviewed, offered, hired, rejected) provided by Employers or generated by workflow actions.</li>
				</ul>
			)
		},
		// ...existing code...
	];

	// Section rendering logic
	// For brevity, only the first three sections are shown above. The rest should follow the same pattern as your original code.

	return (
		<div ref={containerRef} className="max-w-4xl mx-auto py-25 px-4 bg-white rounded-2xl shadow-lg">
			<h1 className="text-4xl font-bold mb-6 text-[#1FAE48] text-center">HIJR Privacy Policy</h1>
			<p className="text-gray-700 mb-8 text-center">Healthcare International Job Recruitment App – Privacy Policy<br/>Last updated: 27 September 2025</p>

			<div className="space-y-8">
				{/* Animated sections */}
				{sections.map((section, idx) => (
					<section
						key={section.title}
						ref={el => sectionRefs.current[idx] = el}
					>
						<h2 className="text-2xl font-semibold text-[#1FAE48] mb-2">{section.title}</h2>
						{section.content}
					</section>
				))}
				{/* ...existing code for remaining sections, table, and annexes... */}
			</div>
		</div>
	);
}
